### ISSUE TITLE
Slower than VlFeat?

### ISSUE THREAD

**Issue by SunQilin** [idiap/mser#1]
I have ran  this mser algorithm. I found it was slower than VlFeat. How it comes?

**Comment by cdubout** [comment]
Can you give me the image and your timings?
Are you sure you compiled both softwares similarly and are using similar options?
I just had a look to VLFeat’s code to see if they updated it but it does not look like it,
they still do not use the linear time MSER algorithm so I find it hard to believe that it
could be faster.
Cheers,

Charles

**Comment by SunQilin** [comment]
Thank you for replying so fast!

The picture I tested is in the attachment.  I use 1.3s to extract msers for source image and inverted image. However, the VlFeat use 1.0s to extract msers in the same image.
Additionally, I used the compiled VlFeat's dll file, not the source file.
Option:
    min_area = 0.0001;
    max_area = 0.5;
    delta = 1;
    max_variation = 0.5;
    min_diversity = 0.33;

Best wishes

sunqilin13@mails.ucas.ac.cn

From: Charles Dubout
Date: 2015-09-02 22:11
To: idiap/mser
CC: SunQilin
Subject: Re: [mser] Slower than VlFeat? (#1)
Can you give me the image and your timings?
Are you sure you compiled both softwares similarly and are using similar options?
I just had a look to VLFeat’s code to see if they updated it but it does not look like it,
they still do not use the linear time MSER algorithm so I find it hard to believe that it
could be faster.
Cheers,

Charles

**Comment by cdubout** [comment]
I think you forgot to attach the image…

**Comment by SunQilin** [comment]
Sorry, the image is attached. Can you see it this time?

sunqilin13@mails.ucas.ac.cn

From: Charles Dubout
Date: 2015-09-03 00:28
To: idiap/mser
CC: SunQilin
Subject: Re: [mser] Slower than VlFeat? (#1)
I think you forgot to attach the image…

**Comment by cdubout** [comment]
Hello,

No I still do not see anything attached.

Charles

**Comment by SunQilin** [comment]
![scenetext01](https://cloud.githubusercontent.com/assets/11513245/9637681/c60b0904-51d4-11e5-81c3-8753cd32fd5b.jpg)

**Comment by SunQilin** [comment]
How about this time?

**Comment by cdubout** [comment]
Yes I got it.
On my machine (a 4 years old MacBookPro), with 1 core i7 at 2.2 GHz, I extracted MSERs from the image and its inverse in 75 ms with my code.
I think you should check that you compiled it in release mode and not debug.
Cheers,

Charles

**Comment by SunQilin** [comment]
OK. It is midnight in China now. I will check it tomorrow. Thank you for your help and patience.

**Comment by SunQilin** [comment]
I'm sorry that I reply you so late. After I get your result, I tried some experiment on your suggestion. The results are disappointing. However, I found that there is something wrong with my VS.  I solved the problem until today. The results are perfect. The algorithm is very fast. Thank you!

**Comment by mlaves** [comment]
So this issue can be closed?

**Comment by SunQilin** [comment]
OK!
